version: '2'
services:
    ocr-app:
        image: ocr
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://ocr-mysql:3306/ocr?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ocr-mysql:
        extends:
            file: mysql.yml
            service: ocr-mysql
